### ISSUE TITLE
Add keywords

### ISSUE THREAD

**Issue by artgibson** [embedly/embedly-docs#1]
We need to add keywords to each tutorial and doc so that they can be surfaced in a search.

**Comment by TrevorBurnham** [comment]
Keyword support has been added to doc-utils. The syntax is

```
.. container:: keywords

   keyword1, keyword2
```

which compiles to

```
<div class="keywords">keyword1, keyword2</div>
```

which is set to `display: none;` via CSS. Ideally, we'd use a meta tag in the `<head>`, but I can't figure out how to get that done from Sphinx, so this feels like an acceptable solution.

**Comment by TrevorBurnham** [comment]
Closing this issue. Just be aware that the feature is available.
