### ISSUE TITLE
Return search results for partial queries

### ISSUE THREAD

**Issue by TrevorBurnham** [embedly/embedly-docs#10]
When you type **embe**, for example, no results are found, even though many results are found for **embed**. Users have been spoiled by Google to expect "fuzzy searching" so that they only have to type in approximate matches. Unfortunately, Searchify doesn't offer fuzzy search in and of itself. I may be able to partially remedy this by performing a combined search containing both what the user has actually entered and what the autocomplete API thinks they're trying to enter.

Alternatively, we may want to give the fresh-out-of-YC [Swiftype](http://swiftype.com/) a whirl... Searchify is just serving Indextank's product, not providing additional innovation.

**Comment by screeley** [comment]
<3 innovation.

**Comment by TrevorBurnham** [comment]
Turns out the answer was simple: Just add a `*` at the end of each search term. [Done and done](https://github.com/embedly/embedly-www/commit/19d02a73955a88bccec929c02084a513be4a8674).
