### ISSUE TITLE
highlight search terms in resulting doc

### ISSUE THREAD

**Issue by tboetig** [embedly/embedly-docs#12]
It does this in search, but it would be nice if they could be highlighted in the document itself.  could be accomplished with a jquery plugin http://bit.ly/JVrNwC, but the term needs to be passed in to the doc

**Comment by TrevorBurnham** [comment]
Implemented as of https://github.com/embedly/embedly-www/commit/c57560909d0a005e91434b27c344bca913485e25.

I think there needs to be a message at the top of the page that says "Highlighting matches for [search]" and provides a link to disable the highlighting.

**Comment by TrevorBurnham** [comment]
Fixed by https://github.com/embedly/embedly-www/commit/45abb2700129c4183daea99f5ac5f145663ba2f9. Here's what it looks like:

![](http://f.cl.ly/items/0E0H2t2b3C3z052s0U3n/Screen%20Shot%202012-07-03%20at%201.23.31%20PM.png)
