### ISSUE TITLE
Persist article navigation

### ISSUE THREAD

**Issue by tboetig** [embedly/embedly-docs#13]
Either have the nav floating as you scroll through the doc, probably to the right of the article, or insert "back to top" links after each section, so the user can get back to the article structure.

**Comment by TrevorBurnham** [comment]
Are we doing this? I like the current (Wikipedia-style) approach to in-page navigation.

A floating TOC can be elegant, but where would you put it within our current design?

"Back to top" links are doable, but they just duplicate what the back button already does. The audience for the long pages is developers; they know how to use a browser.

**Comment by tboetig** [comment]
it sounds like if we add the fixed list of links to endpoint/libraries/tutorials in the left column we don't need to do this.

**Comment by TrevorBurnham** [comment]
Isn't that orthogonal to this issue? This is about in-page navigation, the fixed list is about inter-page navigation.
