### ISSUE TITLE
Fixed links to key docs

### ISSUE THREAD

**Issue by TrevorBurnham** [embedly/embedly-docs#15]
Adding a list of key links to the left sidebar. Looks like this:

![](http://f.cl.ly/items/1F1o3Y1l3m2M1j3C0F3l/Screen%20Shot%202012-05-24%20at%203.48.59%20PM.png)

The list fades out when there's text in the search box, and fades back in when there isn't.

**Comment by TrevorBurnham** [comment]
Fixed by https://github.com/embedly/embedly-www/commit/d6c81a43554c48a91403bc0ef041a3dd5517e94e

**Comment by screeley** [comment]
We have the real estate so let's do sub headings as well.

Endpoints
- oEmbed
- Preview
- Objectify 
- Query Arguments
- Response

Tutorials
- One
- Two
- Etc

Libraries probably doesn't need any sub items.

**Comment by TrevorBurnham** [comment]
I think only pages that developers are likely to reference frequently should be listed in the sidebar. Otherwise, the clutter defeats the intended purpose. So for that reason, I don't think tutorials should be listed individually. How about:

Tutorials

Libraries

API Arguments

API Responses

API Endpoints
- oEmbed
- Preview
- Objectify

**Comment by screeley** [comment]
That's fine. I'd put Arguments and Responses after Endpoints though.

**Comment by TrevorBurnham** [comment]
[Pushed](https://github.com/embedly/embedly-www/commit/54e49ae377230a8b0bf4ce499ddcbcc50476d4ab). Here's how it looks now:

![](http://f.cl.ly/items/3M0D1X360j3P1P1l1k2o/Screen%20Shot%202012-05-29%20at%209.52.56%20AM.png)
