### ISSUE TITLE
Add more tutorials or faq

### ISSUE THREAD

**Issue by artgibson** [embedly/embedly-docs#2]
There are a lot of repeat tickets in our support system , that should be better surfaced in the Doc, Faq, and tutorials sections. Identifiy and start drafting copy.

**Comment by artgibson** [comment]
I have this Tumblr screencast that I created for Embedly Anywhere. We could use this as one of the tutorials with a small write up.

https://embedly.viewscreencasts.com/42762c470357b37c3522c7e304a560e4

**Comment by TrevorBurnham** [comment]
The Tumblr/Embedly Anywhere tutorial is live at http://embed.ly/docs/tutorials/tumblr. Closing the issue. Let me know if there are any other tutorials you'd like to see.
