### ISSUE TITLE
Make Authors and Code clickable.

### ISSUE THREAD

**Issue by screeley** [embedly/embedly-docs#5]
The first thing I want to do when I enter: http://wwwng.embed.ly/docs is click on authors or docs. It's bad that I cannot. 

Search is good from finding something you already know, but we need to also cater to discovery.

**Comment by TrevorBurnham** [comment]
I agree; there isn't a good page for the Authors icon to go to yet, though. I'll have to write one first.

**Comment by screeley** [comment]
Ok, If you need some design done, @tboetig is here to help.

**Comment by TrevorBurnham** [comment]
@tboetig Some design help on the new "Welcome to the Docs" page would be great, esp. with the iconography. See https://github.com/embedly/embedly-docs/issues/3#issuecomment-5627040

**Comment by TrevorBurnham** [comment]
Fixed on master by d4d5ec0d96a29432cf55a2f459ceb32cf53ef316. Check it out at http://wwwng.embed.ly/docs

With this and #6 closed, the new doc features should be ready for prime time.
