### ISSUE TITLE
developer entrance point

### ISSUE THREAD

**Issue by artgibson** [embedly/embedly-docs#7]
The developer entrance point should probably point to this page: http://embed.ly/docs/endpoints
vs. http://embed.ly/docs/tutorials/start

Also we should add a link to our libraries on the developers section of this page: http://wwwng.embed.ly/docs.   , http://embed.ly/docs/libraries

**Comment by TrevorBurnham** [comment]
I've been rewriting `tutorials/start` as something that's aimed more at developers. Let me merge that from rewrite to master.

Let's add links to both `libraries` and `endpoints` from the developer column.

**Comment by artgibson** [comment]
That works.

On Mon, May 21, 2012 at 2:06 PM, Trevor Burnham <
reply@reply.github.com

**Comment by TrevorBurnham** [comment]
Updated the index page to look like this:

![](http://f.cl.ly/items/1o3W0o1v2M2C2U2W1X29/Screen%20Shot%202012-05-21%20at%202.17.17%20PM.png)

Incidentally, I wanted to put a notice at the top of the "Embedly for Authors" and "Getting Started" pages saying "This page is for authors, if you're a developer go to this page" (and vice versa) but ran into a small problem: Italicizing the notice broke the links. I posted an SO question, but haven't gotten a response yet: http://stackoverflow.com/questions/10669099/italicize-text-containing-a-link I suppose I can use raw HTML.

**Comment by TrevorBurnham** [comment]
Please check out http://wwwng.embed.ly/docs now and let me know if there's anything else I can do.

**Comment by artgibson** [comment]
Looks great.
