### ISSUE TITLE
tools and libraries merged?

### ISSUE THREAD

**Issue by artgibson** [embedly/embedly-docs#9]
There is a broken link at the bottom. I'm not sure if the intention was to merge this, but I would suggest a face lift and some re-org.

http://wwwng.embed.ly/docs/libraries

**Comment by artgibson** [comment]
Forgot to assign this to you earlier. This page could use a little clean up.

**Comment by TrevorBurnham** [comment]
Fixed by 68f187c1ec0e3c46d0e6234fcad9a2392e668f7f
